// frame.cxx
// Copyright (c) 2025, 张子辰

// This file is part of HDR Image Frame.

// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions are met:

// 1. Redistributions of source code must retain the above copyright notice, this
//    list of conditions and the following disclaimer.

// 2. Redistributions in binary form must reproduce the above copyright notice,
//    this list of conditions and the following disclaimer in the documentation
//    and/or other materials provided with the distribution.

// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
// AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
// IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
// DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
// FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
// DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
// SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
// CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
// OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
// OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

// Disclosure of Generative AI Usage:
// This file was initially generated by Google Gemini 3 Pro, but thoroughly
// reviewed, debugged, and revised by the author. Please refer to commit
// 5d73a79 for the AI-generated text. Some commits since 04563b4 are done
// with the help of Claude Opus 5, and they might not be properly reviewed.

#include <iostream>
#include <vector>
#include <string>
#include <string_view>
#include <fstream>
#include <cmath>
#include <algorithm>
#include <format>
#include <filesystem>

#include <opencv2/opencv.hpp>
#include <opencv2/imgproc.hpp>
#include <opencv2/imgcodecs.hpp>

#include <exiv2/exiv2.hpp>

#include <ultrahdr_api.h>

#include "filesystem.hxx"
#include "string.hxx"
#include "text_renderer.hxx"
#include "exif.hxx"
#include "arguments.hxx"

using std::clog, std::cerr, std::endl, std::ifstream, std::ofstream, std::ios;
using std::string, std::vector, std::format;
using cv::Mat, cv::Point, cv::Scalar;
using namespace std::string_literals;
using namespace std::string_view_literals;
namespace fs = std::filesystem;

constexpr auto BOLD_FONTS = {"/usr/share/fonts/truetype/noto/NotoSans-Bold.ttf"sv, "/usr/share/fonts/truetype/noto/NotoSansSymbols2-Regular.ttf"sv};
constexpr auto REGULAR_FONTS = {"/usr/share/fonts/truetype/noto/NotoSans-Regular.ttf"sv, "/usr/share/fonts/truetype/noto/NotoSansSymbols2-Regular.ttf"sv};

// The photo sits above a footer holding two lines of text on the left, and the
// camera model, the lens and the manufacturer logo on the right. Every length
// of the frame is derived from the ones below, given in pixels at the reference
// font size DEFAULT_FONT_SIZE and converted to the requested one by scaled().
constexpr int FOOTER_PADDING = 5;     // above the top of the first line
constexpr int DEFAULT_FONT_SIZE = 52; // main text size
constexpr int SUB_FONT_SIZE = 40;     //
constexpr int LINE_SPACING = 70;      // between the baselines of the two lines
constexpr int LOGO_HEIGHT = 120;      // the logo is fitted into this box, ...
constexpr int LOGO_WIDTH = 240;
constexpr int LOGO_SPACING = 40;      // ... this far from the text on its left

bool checkUhdr(uhdr_error_info_t status, const string& msg) {
    if (status.error_code != UHDR_CODEC_OK) {
        cerr << "[UltraHDR] " << msg << " Failed: " << status.error_code;
        if (status.has_detail) cerr << " (" << status.detail << ")";
        cerr << endl;
        return false;
    }
    return true;
}

Mat wrapUhdrImage(uhdr_raw_image_t* img) {
    if (!img) return Mat();
    if (img->fmt == UHDR_IMG_FMT_32bppRGBA8888)
        return Mat(img->h, img->w, CV_8UC4, img->planes[UHDR_PLANE_PACKED]);
    if (img->fmt == UHDR_IMG_FMT_64bppRGBAHalfFloat)
        return Mat(img->h, img->w, CV_16FC4, img->planes[UHDR_PLANE_PACKED]);
    return Mat();
}

bool process(const string &inputPath, const string &outputPath, int quality, int targetW, int targetH, Shrink shrink, int fontSize, int margin, bool verbose) {
    // Every length of the frame is a fixed proportion of the main font size.
    // scaled(n) converts the length n, measured in pixels at the reference font
    // size, to the length at the requested one; hence scaling the canvas and the
    // font size by the same factor yields a visually identical frame.
    auto scaled = [ratio = (double)fontSize / DEFAULT_FONT_SIZE](int length) {
        return (int)std::lround(length * ratio);
    };

    // 1. Read Input
    ifstream file(inputPath, ios::binary | ios::ate);
    if (!file.good()) { cerr << "File error: " << inputPath << endl; return false; }
    size_t size = file.tellg();
    file.seekg(0, ios::beg);
    vector<char> buffer(size);
    file.read(buffer.data(), size);

    // 2. Decode (Dual Pass if UltraHDR)
    Mat sdrMat, hdrMat; // sdrMat is BGR (8u), hdrMat is BGR (32f Linear)
    auto hasHDR = false;

    if(verbose) clog << "Decoding SDR plane..." << endl;
    sdrMat = cv::imdecode(buffer, cv::IMREAD_COLOR);
    if (sdrMat.empty()) { cerr << "Decode failed: " << inputPath << endl; return false; }

    auto exif = getExif(buffer);

    if (is_uhdr_image(buffer.data(), size)) {
        if(verbose) clog << "Decoding HDR plane..." << endl;

        uhdr_codec_private_t* dec = uhdr_create_decoder();
        uhdr_compressed_image_t input_img = { buffer.data(), size, size, UHDR_CG_UNSPECIFIED, UHDR_CT_UNSPECIFIED, UHDR_CR_UNSPECIFIED };
        uhdr_dec_set_image(dec, &input_img);
        uhdr_dec_set_out_img_format(dec, UHDR_IMG_FMT_64bppRGBAHalfFloat);
        uhdr_dec_set_out_color_transfer(dec, UHDR_CT_LINEAR); // Essential for raw linear data
        uhdr_dec_probe(dec);
        if (uhdr_decode(dec).error_code == UHDR_CODEC_OK) {
            auto raw16 = wrapUhdrImage(uhdr_get_decoded_image(dec)); // CV_16FC4

            // Convert 16F -> 32F first to avoid OpenCV cvtColor issues with 16-bit float
            Mat raw32;
            raw16.convertTo(raw32, CV_32F);

            // Now safe to convert Color space on 32F image
            cvtColor(raw32, hdrMat, cv::COLOR_RGBA2BGR);

            hasHDR = true;
        }
        uhdr_release_decoder(dec);
    }

    // 3. Resize & Pad
    int footerHeight = scaled(FOOTER_PADDING + std::max(LINE_SPACING*2,LOGO_HEIGHT));

    // Size of the photo once scaled to fit inside the requested frame.
    double scale = std::min((double)(targetW - margin*2) / sdrMat.cols, (double)(targetH - margin*2 - footerHeight) / sdrMat.rows);
    cv::Size photo(sdrMat.cols * scale, sdrMat.rows * scale);

    // A dimension marked with `~` is only an upper bound: shrink the frame onto
    // the photo, leaving no white space in that direction. The scale is already
    // fixed by the other dimension, which may therefore still be padded.
    if (shrink == Shrink::Width) targetW = photo.width + margin*2;
    else if (shrink == Shrink::Height) targetH = photo.height + margin*2 + footerHeight;

    // Both planes hold the same photo and have to line up, so they share its
    // placement rather than each fitting itself into the frame.
    auto layout = [&](const Mat& src, Mat& dst, Scalar padColor, int interp) {
        int x = (targetW - photo.width) / 2;
        int y = margin + (targetH - margin*2 - footerHeight - photo.height) / 2;

        dst.setTo(padColor);
        Mat resized;
        resize(src, resized, photo, 0, 0, interp);
        resized.copyTo(dst(cv::Rect(x, y, photo.width, photo.height)));
    };

    Mat sdrCanvas(targetH, targetW, CV_8UC3);
    layout(sdrMat, sdrCanvas, Scalar(255, 255, 255), cv::INTER_LANCZOS4);

    Mat hdrCanvas;
    if (hasHDR) {
        hdrCanvas.create(targetH, targetW, CV_32FC3);
        // Pad with 1.0 (SDR White in Linear HDR)
        layout(hdrMat, hdrCanvas, Scalar(1.0f, 1.0f, 1.0f), cv::INTER_LANCZOS4);
    }

    // 4. Draw Metadata
    auto meta = parseExif(exif);
    TextRenderer fontMain(BOLD_FONTS, fontSize);
    TextRenderer fontSub(REGULAR_FONTS, scaled(SUB_FONT_SIZE));

    auto maintext = format("{} ⋅ {} ⋅ {} ⋅ {}", meta.aperture, meta.shutter, meta.focal, meta.iso);
    auto subtext = meta.date;
    if (meta.coordinate != "") {
        (subtext += " ⋅ ") += meta.coordinate;
    }
    int footerY = targetH - footerHeight + scaled(FOOTER_PADDING); // top of the text
    int mainY = footerY + fontSize;              // baseline of the main text
    int subY = mainY + scaled(LINE_SPACING);     // baseline of the sub text

    // SDR Colors
    Scalar sdrText(0,0,0);
    Scalar sdrSub(100,100,100);

    // HDR Colors (Linear)
    // Black is 0. Gray #666 (0.4 sRGB) is approx 0.133 Linear
    Scalar hdrText(0,0,0);
    Scalar hdrSub(0.133, 0.133, 0.133);

    // Draw SDR
    fontMain.render(sdrCanvas, maintext, Point(margin, mainY), sdrText);
    fontSub.render(sdrCanvas, subtext, Point(margin, subY), sdrSub);

    // Draw HDR
    if (hasHDR) {
        fontMain.render(hdrCanvas, maintext, Point(margin, mainY), hdrText);
        fontSub.render(hdrCanvas, subtext, Point(margin, subY), hdrSub);
    }

    // Logos
    auto logoPath = get_executable_directory();
    bool hasMakeLogo = false;
    if (fs::is_directory(logoPath / "../share/hiframe/logo")) logoPath /= "../share/hiframe/logo";
    else if (is_directory(logoPath / "logo")) logoPath /= "logo";
    else if (fs::is_directory(logoPath / "../logo")) logoPath /= "../logo";
    else cerr << "Unable to find logo images" << endl;

    auto m = meta.make; std::transform(m.begin(), m.end(), m.begin(), tolower);
    for (const auto &logo : fs::directory_iterator(logoPath)) {
        auto p = logo.path();
        if (p.filename() == "default.png") continue;
        auto stem = p.stem().string();
        if (m.find(stem) != string::npos) {
            logoPath = p;
            hasMakeLogo = true;
            break;
        }
    }
    if (!hasMakeLogo) {
        cerr << "Unknown manufacture: " << meta.make << "; fallback to default logo" << endl;
        logoPath /= "default.png";
    }

    Mat logo = cv::imread(logoPath, cv::IMREAD_UNCHANGED);
    if (!logo.empty()) {
        if (logo.channels() < 4) cvtColor(logo, logo, logo.channels()==1 ? cv::COLOR_GRAY2BGRA : cv::COLOR_BGR2BGRA);

        auto logosize = logo.size();
        int logoH = scaled(LOGO_HEIGHT), logoW = scaled(LOGO_WIDTH); // box the logo is fitted into
        double logoresize_ratio = std::min((double)logoH/logosize.height, (double)logoW/logosize.width);
        int hsize = std::round(logosize.width*logoresize_ratio);
        int vsize = std::round(logosize.height*logoresize_ratio);
        resize(logo, logo, cv::Size(hsize,vsize), 0, 0, cv::INTER_AREA);
        int lx = targetW - margin - hsize;
        int ly = footerY + (logoH-vsize)/2;

        // Blend SDR
        for(int r=0; r<logo.rows; r++) {
            for(int c=0; c<logo.cols; c++) {
                cv::Vec4b p = logo.at<cv::Vec4b>(r,c);
                float a = p[3]/255.f;
                if(a>0) {
                    cv::Vec3b& b = sdrCanvas.at<cv::Vec3b>(ly+r, lx+c);
                    for(int k=0;k<3;k++) b[k] = cv::saturate_cast<uchar>(b[k]*(1-a) + p[k]*a);
                }
            }
        }

        // Blend HDR (Linear)
        if (hasHDR) {
            for(int r=0; r<logo.rows; r++) {
                for(int c=0; c<logo.cols; c++) {
                    cv::Vec4b p = logo.at<cv::Vec4b>(r,c);
                    float a = p[3]/255.f;
                    if(a>0) {
                        cv::Vec3f& b = hdrCanvas.at<cv::Vec3f>(ly+r, lx+c);
                        for(int k=0;k<3;k++) {
                            // Convert logo sRGB to Linear: pow(x/255, 2.2)
                            float val = pow(p[k]/255.f, 2.2f);
                            b[k] = b[k]*(1-a) + val*a;
                        }
                    }
                }
            }
        }

        int gap = scaled(LOGO_SPACING); // gap between the logo and the text on its left

        string cam = meta.model;
        int w = fontMain.width(cam);
        fontMain.render(sdrCanvas, cam, Point(lx - gap - w, mainY), sdrText);
        if (hasHDR) fontMain.render(hdrCanvas, cam, Point(lx - gap - w, mainY), hdrText);

        if(!meta.lens.empty()) {
            int w2 = fontSub.width(meta.lens);
            fontSub.render(sdrCanvas, meta.lens, Point(lx - gap - w2, subY), sdrSub);
            if(hasHDR) fontSub.render(hdrCanvas, meta.lens, Point(lx - gap - w2, subY), hdrSub);
        }
    }

    // 5. Encode (Raw SDR + Raw HDR)
    if(verbose) clog << "Encoding..." << endl;

    // update some EXIF data regarding the new image.
    if (!exif.empty()) {
        using namespace Exiv2;
        if (auto key = exif.findKey(ExifKey("Exif.Image.Orientation")); key != exif.end())
        exif.erase(key);
        if (auto key = exif.findKey(ExifKey("Exif.Image.ImageWidth")); key != exif.end())
            *key = targetW;
        if (auto key = exif.findKey(ExifKey("Exif.Image.ImageLength")); key != exif.end())
            *key = targetH;
    }

    if (hasHDR) {
        // Prepare Raw Images
        // SDR: Convert BGR to RGBA
        Mat sdrRaw; cvtColor(sdrCanvas, sdrRaw, cv::COLOR_BGR2RGBA);

        // HDR: Convert BGR Linear Float to RGBA Half Float (16F)
        Mat hdrLinear; cvtColor(hdrCanvas, hdrLinear, cv::COLOR_BGR2RGBA);
        Mat hdrHalf; hdrLinear.convertTo(hdrHalf, CV_16F);

        auto enc = uhdr_create_encoder();

        uhdr_raw_image_t sdr_img = { UHDR_IMG_FMT_32bppRGBA8888, UHDR_CG_BT_709, UHDR_CT_SRGB, UHDR_CR_FULL_RANGE,
                                     (unsigned)sdrRaw.cols, (unsigned)sdrRaw.rows };
        sdr_img.planes[UHDR_PLANE_PACKED] = sdrRaw.data;
        sdr_img.stride[UHDR_PLANE_PACKED] = sdrRaw.cols; // Stride in pixels

        uhdr_raw_image_t hdr_img = { UHDR_IMG_FMT_64bppRGBAHalfFloat, UHDR_CG_BT_709, UHDR_CT_LINEAR, UHDR_CR_FULL_RANGE,
                                     (unsigned)hdrHalf.cols, (unsigned)hdrHalf.rows };
        hdr_img.planes[UHDR_PLANE_PACKED] = hdrHalf.data;
        hdr_img.stride[UHDR_PLANE_PACKED] = hdrHalf.cols;

        checkUhdr(uhdr_enc_set_raw_image(enc, &sdr_img, UHDR_SDR_IMG), "Set SDR");
        checkUhdr(uhdr_enc_set_raw_image(enc, &hdr_img, UHDR_HDR_IMG), "Set HDR");
        checkUhdr(uhdr_enc_set_quality(enc, quality, UHDR_BASE_IMG), "Set Base Quality");
        checkUhdr(uhdr_enc_set_quality(enc, quality, UHDR_GAIN_MAP_IMG), "Set Gain Map Quality");

        vector<uint8_t> exif_raw;
        if (!exif.empty()) {
            vector<uint8_t> exif_raw0;
            Exiv2::ExifParser::encode(exif_raw0, Exiv2::littleEndian, exif);

            // The EXIF data encoded by Exiv 2 lacks header, so add it back.
            exif_raw.resize(exif_raw0.size()+6);
            memcpy(exif_raw.data(), "Exif\0", 6);
            memcpy(exif_raw.data()+6, exif_raw0.data(), exif_raw0.size());

            uhdr_mem_block_t eb = { exif_raw.data(), exif_raw.size(), exif_raw.size() };
            checkUhdr(uhdr_enc_set_exif_data(enc, &eb), "Set EXIF");
        }

        if (checkUhdr(uhdr_encode(enc), "Encode")) {
            auto out = uhdr_get_encoded_stream(enc);
            ofstream f(outputPath, ios::binary);
            f.write((char*)out->data, out->data_sz);
            if(verbose) clog << "Saved UltraHDR: " << outputPath << endl;
        }
        uhdr_release_encoder(enc);
    } else {
        // Standard JPEG
        vector<uchar> buf;
        vector<int> p = {cv::IMWRITE_JPEG_QUALITY, quality};
        imencode(".jpg", sdrCanvas, buf, p);
        ofstream f(outputPath, ios::binary);
        f.write((char*)buf.data(), buf.size());
        f.close();

        try {
            Exiv2::Image::AutoPtr dst = Exiv2::ImageFactory::open(outputPath); dst->readMetadata();
            dst->setExifData(exif);
            dst->writeMetadata();
        } catch(...) {}
        if(verbose) clog << "Saved SDR: " << outputPath << endl;
    }

    return true;
}

int main(int argc, char** argv) {
    auto args_op = parse_arguments(argc, argv);
    bool has_failure = false;

    if (std::holds_alternative<int>(args_op))
        return std::get<int>(args_op);
    auto args = std::get<CLIArgs>(args_op);

    for (auto &file: args.files) {
        if (auto ec = create_parent_directory(file.second)) {
            cerr << "Unable to create directory " << file.second.parent_path() << ": " << ec.message() << endl;
            has_failure = true;
            continue;
        }

        if (!process(file.first, file.second, args.quality, args.width, args.height, args.shrink, args.fontsize, args.margin, args.verbose))
            has_failure = true;
    }

    return has_failure? 1:0;
}
